### ISSUE TITLE
'Filecoin.StateMinerInfo' not found

### ISSUE THREAD

**Issue by kimtony** [froghub-io/filecoin-sealer-recover#14]
你好，我跑的时候会报这个方法找不到，lotus是直接用官方代码
![image](https://user-images.githubusercontent.com/34413109/144393310-d4ebf40c-1238-4e52-afce-c1c8910fd095.png)

**Comment by dayou5168** [comment]
你恢复的扇区是多久之前的，很久之前的扇区信息可能你本地并没有，提取不到需要信息，就会修复失败

**Comment by dayou5168** [comment]
另外，你用的是这个工具的哪个版本？

**Comment by kimtony** [comment]
> 你恢复的扇区是多久之前的，很久之前的扇区信息可能你本地并没有，提取不到需要信息，就会修复失败

这个是扇区找不到的错误嘛，像这种的话修复不了嘛

**Comment by kimtony** [comment]
> 另外，你用的是这个工具的哪个版本？

main分支的版本

**Comment by kimtony** [comment]
> > 你恢复的扇区是多久之前的，很久之前的扇区信息可能你本地并没有，提取不到需要信息，就会修复失败
> 
扇区是两天前的，会不会算很久呢

**Comment by dayou5168** [comment]
那应该可以拿到需要的消息的。

**Comment by kimtony** [comment]
> 那应该可以拿到需要的消息的。

这个报错好像说，使用不了miner信息的方法

**Comment by dayou5168** [comment]
发下你的恢复命令

**Comment by dayou5168** [comment]
版本信息也发下。

**Comment by kimtony** [comment]
> 发下你的恢复命令

![mmexport1638459836182](https://user-images.githubusercontent.com/34413109/144454757-a5ccc60d-3221-470a-967e-0533432e8dab.jpg)

**Comment by kimtony** [comment]
> 版本信息也发下。
这个工具版本1.0.0
lotus13.0
bellperson18.0
rust-fil-proofs10.1.0

**Comment by kimtony** [comment]
> 到extern/lotus下执行git log -1 看看lotus是什么版本

我现在不在电脑旁，明天发一下蛤。这个需要对应版本的版本嘛。

**Comment by dayou5168** [comment]
我只是在怀疑……可能是下载的lotus有问题，但是不太确定，因为并没有其它人反馈这个问题。

**Comment by kimtony** [comment]
> 我只是在怀疑……可能是下载的lotus有问题，但是不太确定，因为并没有其它人反馈这个问题。

lotus版本用这个工具生成的版本 也是会出现这种情况。

**Comment by kimtony** [comment]
> 到extern/lotus下执行git log -1 看看lotus是什么版本

![image](https://user-images.githubusercontent.com/34413109/144536746-28d88fc8-0965-472c-aee5-9681c748eb68.png)

**Comment by dayou5168** [comment]
你的lotus daemon版本是，就是你远程调用的那个运行的lotus daemon版本。

**Comment by kimtony** [comment]
> 你的lotus daemon版本是，就是你远程调用的那个运行的lotus daemon版本。

也是这个版本呢

**Comment by FroghubMan** [comment]
> > 到extern/lotus下执行git log -1 看看lotus是什么版本
> 
> ![image](https://user-images.githubusercontent.com/34413109/144536746-28d88fc8-0965-472c-aee5-9681c748eb68.png)

编译没看出问题。


你使用的full node api 的daemon节点是否是修改版本，关闭了所需要的接口。
你可以尝试使用`export FULLNODE_API_INFO=http://13.58.8.193:21234`，再次执行修复，是否还会出现同样的问题。

**Comment by kimtony** [comment]
> > > 到extern/lotus下执行git log -1 看看lotus是什么版本
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/34413109/144536746-28d88fc8-0965-472c-aee5-9681c748eb68.png)
> 
> 编译没看出问题。
> 
> 你使用的full node api 的daemon节点是否是修改版本，关闭了所需要的接口。 你可以尝试使用`export FULLNODE_API_INFO=http://13.58.8.193:21234`，再次执行修复，是否还会出现同样的问题。

谢谢~ 可以跑起来，确实是代码版本的问题，我找一下修改看看。ip能否先借我跑完一个测试呢，我刚跑起来，想看一下修复流程。

**Comment by Funarp** [comment]
> > > 到extern/lotus下执行git log -1 看看lotus是什么版本
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/34413109/144536746-28d88fc8-0965-472c-aee5-9681c748eb68.png)
> 
> 编译没看出问题。
> 
> 你使用的full node api 的daemon节点是否是修改版本，关闭了所需要的接口。 你可以尝试使用`export FULLNODE_API_INFO=http://13.58.8.193:21234`，再次执行修复，是否还会出现同样的问题。

请问还有FULLNODE_API可以进行测试的吗？

**Comment by FroghubMan** [comment]
如果上面的api不能使用的话，那么我这没有公开的了。
