### ISSUE TITLE
Which kind of lotus daemon can be used with filecoin-sealer-recover?

### ISSUE THREAD

**Issue by Shekelme** [froghub-io/filecoin-sealer-recover#15]
I wonder if sealer-recover should be connected to just any lotus daemon (empty isolated node without wallets), or exactly to that daemon that served the miner affected by sectors' corruption?

**Comment by dayou5168** [comment]
Rabin. i think i reply in slack. but i will paste my answer here: `Any lotus damon node is okay. but if you recover sectors long time ago. maybe you need an old lotus daemon or full chain daemon. but sealer-recover is totally green. it doesn't require private key, and don't require access right. you can even recover other miner's secotor`

**Comment by dayou5168** [comment]
And a short answer. you can connect a `empty isolated node without wallets` to recover a sector.
