### ISSUE TITLE
Can recover support two Nvidia Card?

### ISSUE THREAD

**Issue by Funarp** [froghub-io/filecoin-sealer-recover#22]
https://github.com/froghub-io/filecoin-sealer-recover/blob/3ba9e489a92c431815ffd827e57e3874a92bc36d/recovery/recover.go#L248

According to code below, It seems P2Lock is single, So only one P2 work to do at once?

can two card run two P2 work at same time?

**Comment by FroghubMan** [comment]
The original program of lotus also only supports a single p2, which is executed one by one in sequence. If you have done your own optimization, it is recommended that you adjust the lock mechanism of the recovery program to achieve what you want.

**Comment by Funarp** [comment]
Would you like to share P2 optimization?
