### ISSUE TITLE
获取扇区ticket错误

### ISSUE THREAD

**Issue by printinfo** [froghub-io/filecoin-sealer-recover#4]
错误提示:
Getting sector (6) ticket error: Miner(fxxxx) Sector(6) info Not Found
这个扇区在proving状态，但是文件丢了
扇区commit有点久了，在上个月的时候

**Comment by FroghubMan** [comment]
这样的扇区只提交了precommit消息，超时未提交provecommit消息，预质押的fil已经被销毁，扇区失效了，没有恢复的必要了。

**Comment by FroghubMan** [comment]
问题已经修复，issue我先关闭了，如果还存在同样的问题您再打开，或者开启新的issue
