### ISSUE TITLE
PreCommitInfo报错

### ISSUE THREAD

**Issue by AnonymousJavaer** [froghub-io/filecoin-sealer-recover#7]
执行StateSectorPreCommitInfo的时候报错，这是几个月前上链的一个扇区，现在OnChain和Active都是Yes

EXTRA *jsonrpc.respError=(get sset) failed to load miner actor: load state tree: failed to load state tree bafy2bzacec3cvflydfyy64uifinqyrtt6rjovnlxuhp7c7r6ifddojgc7ujdi: failed to load hamt node: blockstore: block not found

怀疑是因为对daemon同步的数据有裁剪，导致找不到几个月前的区块，但不是很确定

**Comment by AnonymousJavaer** [comment]
用区块链浏览器查了一下，确实没有这个block，但是tipset时间是对的

**Comment by wenxinnnnn** [comment]
是裁剪的问题，你找一个旧节点取数据吧

**Comment by FroghubMan** [comment]
是这个问题，找个旧的链节点吧

**Comment by AnonymousJavaer** [comment]
> 是这个问题，找个旧的链节点吧

请问下有没有办法换个接口来拿数据呢，按理说这些信息都是存在链上的，本地没有为啥daemon不去链上找？ 主要同步数据太大了，不裁剪的话很浪费空间

**Comment by FroghubMan** [comment]
如果需要恢复数据的miner节点还是存在的话，那么可以使用sector info相关的接口获取
